return {
  "stevearc/conform.nvim",
  opts = {
    -- Add or modify the formatters for relevant filetypes
    -- formatters_by_ft = {
    --   -- ... other filetypes
    --   javascript = { "eslint_d" }, -- Example: Try eslint_d first, then prettier
    --   javascriptreact = { "eslint_d" },
    --   typescript = { "eslint_d" },
    --   typescriptreact = { "eslint_d" },
    --   -- vue = { "eslint_d"}, -- if you use vue
    --   -- json = { "prettier" },
    --   -- jsonc = { "prettier" },
    --   markdown = { "eslint_d" },
    --   yaml = { "eslint_d" },
    --   html = { "eslint_d" },
    --   css = { "eslint_d" },
    --   scss = { "eslint_d" },
    --   -- Fallback to 'eslint' if eslint_d is not available
    --   -- javascript = { "eslint", "prettier" },
    --   -- javascriptreact = { "eslint", "prettier" },
    --   -- typescript = { "eslint", "prettier" },
    --   -- typescriptreact = { "eslint", "prettier" },
    --   -- vue = { "eslint", "prettier" },
    -- },
    -- Set up the 'eslint_d' or 'eslint' formatter
    -- formatters = {
    --   eslint_d = {
    --     command = "eslint_d",
    --     args = { "--stdin", "--fix", "--quiet", "--allow-empty" },
    --     -- You might need to adjust cwd or other options depending on your setup
    --   },
    --   eslint = {
    --     command = "eslint",
    --     args = { "--stdin", "--fix", "--quiet", "--allow-empty" },
    --     -- You might need to adjust cwd or other options depending on your setup
    --   },
    --   -- Ensure prettier is also configured if you use it
    --   prettier = {
    --     command = "prettier",
    --     args = {
    --       "--stdin-filepath",
    --       vim.fn.fnameescape(vim.api.nvim_buf_get_name(0)),
    --       "--single-quote",
    --       "--jsx-single-quote",
    --       "--trailing-comma",
    --       "all",
    --       "--print-width",
    --       "100",
    --     },
    --     -- Add other prettier args based on your .prettierrc if needed
    --   },
    -- },
  },
}
